// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gateway_api_final.Entities;

namespace gateway_api_final.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("gateway_api_final.Model.Gateway", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SerialNumber");

                    b.ToTable("Gateways");
                });

            modelBuilder.Entity("gateway_api_final.Model.Peripheral", b =>
                {
                    b.Property<uint>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTimeOffset?>("CreationDate")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GatewayId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UId");

                    b.HasIndex("GatewayId");

                    b.ToTable("Peripherals");
                });

            modelBuilder.Entity("gateway_api_final.Model.Peripheral", b =>
                {
                    b.HasOne("gateway_api_final.Model.Gateway", "Gateway")
                        .WithMany("AssociatedPeripherals")
                        .HasForeignKey("GatewayId");

                    b.Navigation("Gateway");
                });

            modelBuilder.Entity("gateway_api_final.Model.Gateway", b =>
                {
                    b.Navigation("AssociatedPeripherals");
                });
#pragma warning restore 612, 618
        }
    }
}
