-- MySQL Script generated by MySQL Workbench
-- Sun Oct 17 01:29:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GatewaysBd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GatewaysBd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GatewaysBd` DEFAULT CHARACTER SET utf8 ;
USE `GatewaysBd` ;

-- -----------------------------------------------------
-- Table `GatewaysBd`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GatewaysBd`.`User` ;

CREATE TABLE IF NOT EXISTS `GatewaysBd`.`User` (
  `UserId` CHAR(36) NOT NULL,
  `Name` NVARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GatewaysBd`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GatewaysBd`.`Account` ;

CREATE TABLE IF NOT EXISTS `GatewaysBd`.`Account` (
  `AccountId` CHAR(36) NOT NULL,
  `DateCreated` DATE NOT NULL,
  `AccountType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AccountId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GatewaysBd`.`Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GatewaysBd`.`Brand` ;

CREATE TABLE IF NOT EXISTS `GatewaysBd`.`Brand` (
  `Id` CHAR(36) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GatewaysBd`.`Gateway`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GatewaysBd`.`Gateway` ;

CREATE TABLE IF NOT EXISTS `GatewaysBd`.`Gateway` (
  `Id` CHAR(36) NOT NULL,
  `Name` NVARCHAR(45) NOT NULL,
  `status` NVARCHAR(45) NULL,
  `Brand_Id` CHAR(36) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Gateway_Brand_idx` (`Brand_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Gateway_Brand`
    FOREIGN KEY (`Brand_Id`)
    REFERENCES `GatewaysBd`.`Brand` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
